### ISSUE TITLE
.

### ISSUE THREAD

**Issue by lance8765** [LiEnby/chovy-sign#31]
.

**Comment by lance8765** [comment]
I think i've already found a solution... sort of.

First, you download a tool named "psxtract" and copy the EBOOT.PBP in the executable.

Then it creates a BIN/CUE image of the PSOne Classic, with the various icons in a separate folder.

And finally i can convert the BIN/CUE to a format compatible with Content Manager.

The problem is, i must sacrifice the KEYS.BIN and DOCUMENT.DAT files (the second one is probably the game manual)

So yeah, is there a way to keep the manual file inside the converted file?

**Comment by LiEnby** [comment]
there are a few issues here;

 PS1 Eboot are not a single "format" there is multi disc PS1, and single disc PS1.
and then theres the PSX2PSP format (which is different to the offical sony format for PS1 eboots) 

as it stands, chovy-sign2 is the only tool that can create EBOOT.PBP in the offical SONY format. i have actually considered making that a standalone thing since its probably useful on the PSP and PS3 as well. 

unfortunately the SONY eboot format is encrypted with a unique per-game key, that a "hash" of exists in the EBOOT and the key itself is in the license file, the way the hashing algorithm works is flawed and is actually reversable. but.
you can't fake the license file (on OFW anyway) the ECDSA signing keys never leaked for RIFs .. (in fact, if they did you could even break VITA games DRM)

but they did for PGD/DNAS which is used for the PS1 games EBOOTS. so the way chovy-sign works is to just encrypt any random ISO *with* the keys for some license you do have.. ex; spyro the dragon encrypted with the keys from the ape quest demo, works because you have a license for the ape quest demo, so the vita just sees it as if its running that.

anyway this whole process reconstructs the entire EBOOT.PBP from scratch, and EBOOT.PBP is just a weird container for a BIN/CUE without ECC data. 

so making this work would require first extracting ISO data then recreating it again in a new PBP. 
and that would probably be alot of effort. though worth noting that .. there actually is an app that does this, by SquallATF its "PBPResign" and is very much a basis for chovy-sign itself. it was never even meant to be released properly but the source code can be found *here* https://github.com/LiEnby/chovy-sign/tree/master/PbpResign

i dunno if it does document.dat. iirc thats just a giant PGD and probably is easy enough to make work

**Comment by LiEnby** [comment]
Chovy-Trans works becuase the PSP has license files for the vita, and the vita is backwards-compatible with PSP license files for some reason. even though you could never encounter them via normal use (a fact nopspemudrm takes advantage of)

**Comment by LiEnby** [comment]
i had linked a compiled build of PBPResign over on silica.codes earlier on a related page here: https://silica.codes/Li/chovy-sign/issues/16#issuecomment-537

I still haven't released it as a proper standalone tool because it's not really my code at all. i don't think Squall would actually mind since they basically gave me that and a few other libraries they wrote to use to make the whole PS1 ISO's thing possible, but still.
